---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: false

# which roles to test
env:
  - ROLE=matrix-synapse

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

script:
  - ansible-playbook $ROLE/tests/test.yml -i $ROLE/tests/inventory --syntax-check
  - ansible-lint -x701 $ROLE
