---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: false

# which roles to test
env:
  - ROLE=matrix-synapse

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook $ROLE/tests/test.yml -i $ROLE/tests/inventory --syntax-check
