--- 
- name: "Create an ldap {{ service_cn }} service user (without mail)"
  ldap_entry:
    dn: "cn={{ service_cn }},ou=Services,{{ ldap.base_dn }}"
    objectClass:
      - person
    attributes:
      sn: "{{ service_cn | capitalize }}"
    bind_dn: "{{ ldap.cnadmin_dn }}"
    bind_pw: "{{ ldap.cnadmin_password }}"
  delegate_to: "{{ ldap.ansible_access_ip }}"
  when:
    - mail is defined and not mail or mail is undefined

- name: "Create an ldap {{ service_cn }} service user (with mail)"
  ldap_entry:
    dn: "cn={{ service_cn }},ou=Services,{{ ldap.base_dn }}"
    objectClass:
      - person
      - d120mailService
    attributes:
      sn: "{{ service_cn | capitalize }}"
      mailAlias: "{{ mail_alias }}"
      uid: "{{ service_cn }}"
    bind_dn: "{{ ldap.cnadmin_dn }}"
    bind_pw: "{{ ldap.cnadmin_password }}"
  delegate_to: "{{ ldap.ansible_access_ip }}"
  when:
    - mail is defined
    - mail is true

- name: "Set bind dn password"
  ldap_attr:
    dn: "cn={{ service_cn }},ou=Services,{{ ldap.base_dn }}"
    name: userPassword
    values: "{{ password }}"
    state: exact
    bind_dn: "{{ ldap.cnadmin_dn }}"
    bind_pw: "{{ ldap.cnadmin_password }}"
  delegate_to: "{{ ldap.ansible_access_ip }}"

- name: "Add bind dn to serviceuser group"
  ldap_attr:
    dn: "{{ ldap.serviceuser_cn }}"
    name: member
    values:
      - "cn={{ service_cn }},ou=Services,{{ ldap.base_dn }}"
    state: present
    bind_dn: "{{ ldap.cnadmin_dn }}"
    bind_pw: "{{ ldap.cnadmin_password }}"
  delegate_to: "{{ ldap.ansible_access_ip }}"
