---
- name: "Create PostgreSQL database 'keycloak'."
  postgresql_db:
    name: "{{ keycloak.db.database }}"
    encoding: UTF-8
    state: present
  tags: keycloak

- name: "Create PostgreSQL user 'keycloak' with 'keycloak.*:ALL'."
  postgresql_user:
    db: "{{ keycloak.db.database }}"
    name: "{{ keycloak.db.username }}"
    password: "{{ keycloak.db.password }}"
    priv: ALL
  tags: keycloak

- name: "Create unpriviledged user for running Keycloak."
  user:
    name: keycloak
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  tags: keycloak

- name: "Create required directories."
  file:
    path: /root/ansible-keycloak
    state: directory
  tags: keycloak

- name: "Download Keycloak tarball."
  get_url:
    url: "{{ keycloak.settings.dist_url }}"
    checksum: "{{ keycloak.settings.dist_hash }}"
    dest: "/root/ansible-keycloak/keycloak.tar.gz"
  tags: keycloak

- name: "Unpack Keycloak tarball."
  unarchive:
    src: "/root/ansible-keycloak/keycloak.tar.gz"
    dest: /root/ansible-keycloak
    remote_src: true
    creates: "/root/ansible-keycloak/{{ keycloak.settings.dist_dir }}"
  register: unpacking
  notify: restart keycloak
  tags: keycloak

- name: "Copy Keycloak files in place."
  copy:
    src: "/root/ansible-keycloak/{{ keycloak.settings.dist_dir }}/"
    dest: "{{ keycloak.settings.dest }}"
    remote_src: true
    owner: keycloak
    group: keycloak
    force: true
    mode: u=rwX,g=rX,o=
  when: unpacking.changed
  notify: restart keycloak
  tags: keycloak

- name: "Install Keycloak theme"
  copy:
    src: "files/themes/d120/"
    dest: "{{ keycloak.settings.dest }}/themes/d120/"
    owner: keycloak
    group: keycloak
    mode: u=rwX,g=rX,o=
  tags: keycloak


- name: "Configure Keycloak."
  template:
    src: templates/keycloak.conf.j2
    dest: "{{ keycloak.settings.dest }}/conf/keycloak.conf"
    owner: keycloak
    group: keycloak
    mode: "0600"
  notify: restart keycloak
  tags: keycloak

- name: "Deploy SystemD files."
  template:
    src: templates/keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
  tags: keycloak

- name: "Ensure keycloak is started and enabled on boot."
  service:
    name: keycloak
    state: started
    enabled: true
    daemon_reload: true
  tags: keycloak

- name: "Install KCADM."
  alternatives:
    name: kcadm
    link: /usr/bin/kcadm
    path: "{{ keycloak.settings.dest }}/bin/kcadm.sh"
  tags: keycloak
