---
- block:
    - name: Set server name
      template:
        src: server_name.yml.j2
        dest: /etc/matrix-synapse/conf.d/server_name.yaml

    - name: Add postgres database
      postgresql_db:
        name: "{{ matrix.db.name }}"
        encoding: 'UTF8'
        lc_collate: 'C'
        lc_ctype: 'C'
        template: 'template0'
        #owner: "{{ matrix.db.user }}"
        state: present

    - name: Add matrix postgres user
      postgresql_user:
        db: "{{ matrix.db.name }}"
        name: "{{ matrix.db.user }}"
        password: "{{ matrix.db.password }}"
        priv: ALL
        state: present

    - name: Copy matrix config
      template:
        src: homeserver.yml.j2
        dest: /etc/matrix-synapse/homeserver.yaml
        daemon_reload: true
      notify: restart synapse

  tags: matrix, matrix-config
