---
- name: Converge
  hosts: all
  tasks:
    - name: "Install curl"
      apt:
        name: curl
        state: present
    - name: "Include matrix-synapse"
      include_role:
        name: "matrix-synapse"
