---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  ansible-lint -x 701
platforms:
  - name: instance
    image: jrei/systemd-debian:latest
    pre_build_image: false
    priviliged: true
    tty: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      hash_behaviour: merge
verifier:
  name: testinfra
